### ISSUE TITLE
Failed to activate the atom-modify package

### ISSUE THREAD

**Issue by RStrydom** [amesarosh/atom-modify#3]
1. I installed the atom modify package.
2. Switched to another tab and highlighted the text I wanted to convert.
3. Held down `cmd + alt + m`.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-modify](https://github.com/amesarosh/atom-modify) package, v0.1.0

### Stack Trace

Failed to activate the atom-modify package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/renierstrydom/.atom/packages/atom-modify/lib/atom-modify.coffee:4:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)
```

### Commands

```
     -0:01.0 atom-modify:convert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "slack-chat"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-modify, v0.1.0
color-picker, v2.0.7
language-apache, v1.3.0
minimap, v4.10.1
pigments, v0.8.2
project-manager, v1.15.10
project-view, v0.1.2

# Dev
No dev packages
```

**Comment by CamJN** [comment]
patch in https://github.com/amesarosh/atom-modify/pull/5
